
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build image
      env:
        SHA: ${{ github.sha }}
      run: |
        echo $SHA
        docker build -t dorakueyon/multi-client:latest -t dorakueyon/multi-client:$SHA -f ./client/Dockerfile ./client
        docker build -t dorakueyon/multi-server:latest -t dorakueyon/multi-server:$SHA -f ./server/Dockerfile ./server
        docker build -t dorakueyon/multi-worker:latest -t dorakueyon/multi-worker:$SHA -f ./worker/Dockerfile ./worker
    - name: docker login
      env:
        DOCKERHUB_USER: ${{ secrets.dockerhub_user }}
        DOCKERHUB_PASS: ${{ secrets.dockerhub_pass }}
      run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - name: push image
      env:
        SHA: ${{ github.sha }}
      run: |
        docker push dorakueyon/multi-client:latest
        docker push dorakueyon/multi-server:latest
        docker push dorakueyon/multi-worker:latest
        docker push dorakueyon/multi-client:$SHA
        docker push dorakueyon/multi-server:$SHA
        docker push dorakueyon/multi-worker:$SHA
